Coffect/coffect-BE

.github/workflows/blank.yml

- 관련 이슈: #1 
---
---
0. .github/workflow 파일 생성 
1. CICD 초기 설정
---
---

[Docs] CI/CD init Setting

---

tsoa.json

- 관련 이슈: #13 
---
---
* controllerPathGlobs에서 "src/**/.Controller/.controller.ts" 를 *.Controller.ts 로 수정
---
예시:
---

fix:tsoa.json controllerPathGlobs route change

---

.eslintrc.json

#15 
예시:
- 관련 이슈: #45
---
---
eslint의 에러레벨을 error -> warn으로 수정했습니다.
추가적으로 prettier에서 줄바꿈 시퀀스를 LF로 자동 수정하는 코드를 설정했는데
vscode나 에디터 자체에서 추가적으로 설정이 필요해보입니다. eslint에서 해당 부분은 warn으로 설정 안해놨으니 에디터 설정바랍니다.

refactor : eslint 에러레벨 수정#15

---

@types/express.d.ts
package.json
src/config/swagger.json
src/config/tsoaResponse.ts
src/index.ts
src/middleware/error.ts
src/routes/tsoaRoutes.ts
src/user/user.Controller/user.Controller.ts
src/user/user.Message/user.Message.ts

예시:
- 관련 이슈: #45
#19 
---
---
예시:
1. tsoa 응답 통일
다음과 같은 형식으로 tsoa 컨트롤러에서 성공응답을 통일했습니다.
구체적인 설명은 노션에 업로드하겠습니다.
```
export interface ITsoaErrorResponse {
resultType: string;
error: {
errorCode?: string,
reason?: string | null,
data?: any | null
};
success: null;
};
export interface ITsoaSuccessResponse<T> {
resultType: string;
error: null;
success: T;
}
```
2. 에러 처리 미들웨어
에러 처리 미들웨어 추가했습니다.
커스텀에러 처리할 수 있도록 했고, 그 외의 500번 서버 에러도 처리할 수 있습니다.
```
//에러 처리 미들웨어
export const errorHandler = (err: Error, req: Request, res: Response, next: NextFunction) => {
if(res.headersSent){
next(err);
return;
}
//커스텀 에러 처리
if(err instanceof BasicError){
res.status(err.statusCode).json({ …
```

feat: tsoa 응답 통일, 에러 처리 미들웨어 #19

---

.github/workflows/deploy.yml
package-lock.json
package.json
src/config/s3.ts

---
* ../config/s3.ts 파일 추가하여 upload라는 함수 제작
<pre>
const upload = multer({
storage : multerS3 ({
s3 : settingS3,
bucket : process.env.S3_NAME || '',
acl : 'public-read', // 공개적으로 읽을 수 있게 설정
metadata : function (req, file, cb) {
cb(null, { fileName : file.filename });
},
key : function (req, file, cb) {
cb(null, `${file.originalname}-${uuidv4}`);
}
})
});
</pre>
- upload.single('image'), upload.array('images', n)로 사용 가능
- upload route에 따라 s3파일 경로를 설정해주어야함.
* 예를 들어 user profile에서 업로드 시 S3에서는 /user/:userId 라는 폴더로 넣을 수 있게 만들어야함. 
* /thread라면 /thread/:threadId 라는 폴더를 만들어서 이미지를 넣으면 좋다.
<pre>
<code>
const userUploader = createUploader((req) => {
const userId = req.user?.id;
return `user/${userId}`;
});
router.post('/user/fixUserProfile', userUploader.single('image'), (req, res) => {
res.json({ …

feat: add S3 setting

---

package-lock.json
package.json
src/config/db.config.ts

- 관련 이슈: #29 
---
---
* DB 접속을 위한 Config 파일 제작
* local에서는 port 번호 3307로 접속하게 만들었기 때문에 EC2 상과 local 상에서 구분을 하여야함.
* connctionConfig를 동적으로 바꾸어 .env를 확인 후 host와 port를 구분할 수 있도록 만듬.
<pre>
.env setting
local 환경
- ENV=local
EC2 환경
- ENV = EC2
</pre>
* 사용 시 pool을 import 하여 사용
---
예시:
---

feat: db config setting

---

.gitignore

#37 
예시:
- 관련 이슈: #45
---
---
예시:
swagger.json과 tsoaRoutes.ts는 자동 생성 파일이므로 커밋 대상이 되면 안됩니다.
pull 과정에서 충돌을 방지하기 위해 두 파일을 추가합니다.
다른 코드가 추가되면 다시 생성해야하므로 npm run dev 명령어로 반드시 빌드해주어야 합니다.
---
예시:
---

refactor: gitignore fixed - include swagger.json and tsoaRoutes.ts #37

---

src/routes/tsoaRoutes.ts

---
---
* tsoaRoutes에서 git conflit 문제로 수정 중 }, 를 없애고 만들었음.
---
예시:
---

fix: git conflit tsoaRoute.ts 문제 해결

---

src/coffeeChat/coffeeChat.Model.ts
src/config/swagger.json
src/routes/tsoaRoutes.ts
src/thread/thread.Repository.ts
src/user/user.Controller.ts

예시:
- 관련 이슈: #51 
---
---
prisma, error type any 수정
restult.map에서 any 타입으로 임시방편 수정
---
예시:
---

fix: type Error fix

---

prisma/schema.prisma
src/coffeeChat/coffeeChat.Model.ts
src/config/prisma.config.ts
src/config/scheduler.ts

- 관련 이슈: #53 
---
---
<pre>
<code>
generator client {
provider = "prisma-client-js"
// output   = "../generated/prisma"
}
</code>
</pre>
* output 주석 처리 및 import 값들 변경
---
예시:
---

fix: prisma default route fix

---

prisma/schema.prisma
src/coffeeChat/coffeeChat.Model.ts
src/config/scheduler.ts

- 관련 이슈: #54 
---
---
Prisma Route 경로 수정
---
예시:
---

fix: prisma import route

---

src/coffeeChat/coffeeChat.Model.ts
src/config/scheduler.ts

- 관련 이슈: #53 
---
---
prisma route fixed
---
예시:
---

fix: prisma route fix

---

prisma/schema.prisma
src/coffeeChat/coffeeChat.Controller.ts
src/coffeeChat/coffeeChat.Model.ts
src/coffeeChat/coffeeChat.Service.ts
src/config/swagger.json
src/middleware/coffectChat.DTO/coffectChat.DTO.ts
src/routes/tsoaRoutes.ts

예시:
- 관련 이슈: #45
---
---
* 나의 커피챗 기록 불러오기 구현
<pre> <code> 
opponentName : string;
color1 : string;
color2 : string;
coffeeDate : Date;
</code></pre>
* 나의 커피챗 기록에서 상세 커피챗 불러오기
<pre> <code> 
opponentName : string;
color1 : string;
color2 : string;
coffeeDate : Date;
location : string;
firstUserImage : string;
secondUserImage : string;
</code></pre>
---
예시:
---

feat:jun my page coffee chat

---

src/middleware/thread.DTO/thread.DTO.ts
src/thread/thread.Controller.ts
src/thread/thread.Service.ts

예시:
- 관련 이슈: #45
---
---
예시:
bigint 자료형 수정
---
예시:
---

fix: thread main type fix

---

src/config/s3.ts
src/middleware/detailProfile.DTO/detailProfile.DTO.ts
src/profile/profile.Controller.ts
src/profile/profile.Model.ts
src/profile/profile.Service.ts
src/thread/thread.Model.ts
src/thread/thread.Service.ts
src/user/user.Controller.ts
src/user/user.Model.ts

---
---
profile 관련 기능을 구현했다.
본인 
- 프로필 조회,수정
- 관심사 수정
- 게시글 조회
- 상세프로필 조회, 수정
타인
- 프로필 조회
- 게시글 조회
- 상세프로필 조회
---
예시:
---
interest 부분에 대해 매핑과정이 지나치게 반복되는것 같아 데이터 다루는 방법을 다시 생각해야할듯

[feat] profile 관련 기능 구현

---

src/middleware/thread.DTO/thread.DTO.ts
src/thread/thread.Controller.ts
src/thread/thread.Message.ts
src/thread/thread.Model.ts
src/thread/thread.Service.ts

예시:
- 관련 이슈: #45
- #84 
---
---
예시:
게시글 수정, 삭제 API 추가했습니다.
추가로 로그인 인증이 필요한 기능에 security 작업 완료했습니다.
---
예시:
---

[feat] 게시글 수정, 삭제 API

---

src/coffeeChat/coffeeChat.Controller.ts
src/coffeeChat/coffeeChat.Model.ts
src/coffeeChat/coffeeChat.Service.ts
src/config/scheduler.ts
src/index.ts
src/middleware/coffectChat.DTO/coffectChat.DTO.ts

- 관련 이슈: #72 
---
---
[fix]
* /home/getCardClose
-> 관심 정보를 토대로 User 카드 추천하는 로직
-> 카드 Skip이나 다음 카드를 찾을 때 사용하면 된다.
* scheduler.ts 
-> 작동이 되지 않는 것 같아 한국 시간 UTF 시간 기준으로 수정 
-> Index.ts 에 import 하여 수행되기를 기대하고 있음.
[feat]
* /home/currentCardRecommend
-> 현재 index 기반으로 사용자 Card 불러오는 API
---
예시:
---

[Feat] coffee chat api fixed

---

src/middleware/thread.DTO/thread.DTO.ts
src/thread/thread.Controller.ts
src/thread/thread.Message.ts
src/thread/thread.Model.ts
src/thread/thread.Service.ts

예시:
- 관련 이슈: #45
- #89 
---
---
예시:
게시글 댓글 작성 API, 댓글 조회 API, 이미지 업로드 API까지 완성했습니다.
게시글 이미지까지 불러오는 API도 곧 수정하겠습니다.
---
예시:
---

[feat] 게시글 스크랩, 댓글, 이미지 업로드 API

---

src/coffeeChat/coffeeChat.Controller.ts
src/coffeeChat/coffeeChat.Service.ts
src/follow/follow.Controller.ts

- 관련 이슈: #93 
---
---
* middleWare to Security Changed 
* currentCardRecommend fixed
---
예시:
---

[refac] middleWare to Security Changed && currentCardRecommend fixed

---

src/coffeeChat/coffeeChat.Model.ts
src/middleware/coffectChat.DTO/coffectChat.DTO.ts

- 관련 이슈: #95 
---
---
Date값이 이상하게 나오는 문제 수정
일수로 변환 후 게산
---
예시:
---

fix: date to number

---

src/middleware/error.ts
src/thread/thread.Controller.ts
src/thread/thread.Model.ts
src/thread/thread.Service.ts

예시:
- 관련 이슈: #45
#100 
---
---
예시:
에러 핸들링 미들웨어에 tsoa validation 에러를 핸들링 할 수 있는 코드를 추가했습니다.
---
예시:
---

[refactor] tsoa validation 에러 핸들링 추가

---

src/middleware/detailProfile.DTO/detailProfile.DTO.ts
src/profile/profile.Model.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

feat : profile id 값 추가

---

src/coffeeChat/coffeeChat.Service.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: logic

---

prisma/schema.prisma

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: prisma enum value

---

prisma/schema.prisma
src/follow/follow.Controller.ts
src/follow/follow.Message.ts
src/follow/follow.Model.ts

- 관련 이슈: 
---
---
Follow 로직에서 UserId가 PK인 문제 해결
같은 사람이 여러명을 Follow 걸시 usreId가 PK값이기 때문에 PK 제 1정규화 문제가 생김
userId -> id (자동 증분)으로 수정하여 1정규화 문제를 해결함
같은 User가 여러 명에게 Follow를 걸었을 시 문제가 발생하지 않음
---
예시:
---

[fix] follow unique userId to id Auto

---

src/middleware/detailProfile.DTO/detailProfile.DTO.ts
src/middleware/thread.DTO/thread.DTO.ts
src/thread/thread.Controller.ts
src/thread/thread.Model.ts
src/thread/thread.Service.ts

예시:
- 관련 이슈: #45
#117 
---
---
예시:
게시글 불러오기에 프론트 요청사항 모두 반영하였습니다.
이미지 정보와 유저 정보가 더 구체적으로 제공되고, 응답 객체도 예쁘게 바꿔놓았습니다.
커서 기반 페이지네이션도 구현하였지만, 구현적으로 인기순 정렬은 페이지네이션이 까다롭습니다.
커서 기반으로 힘들다면 오프셋 기반으로 일단 구현하는 방향으로 가야할 것 같습니다.
---
예시:
---

[refactor] 게시글 메인 화면 API 개선

---

prisma/schema.prisma
src/profile/profile.Controller.ts
src/profile/profile.Message.ts
src/profile/profile.Model.ts
src/profile/profile.Service.ts

예시:
- 관련 이슈: #45
#130 
---
---
예시:
시간표 생성, 조회, 수정 API를 추가했습니다.
추가적인 로직이 필요한 경우 리팩토링 진행하겠습니다.
---
예시:
---

[feat] 유저 시간표 관련 api

---

.github/workflows/backup.yml
.github/workflows/deploy.yml
src/config/fcm.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: remove private key

---

package-lock.json
package.json
prisma/mysql/schema.prisma

- 관련 이슈: #128 
---
---
prisma shcema default updateAt added
---
예시:
---

fix: updateAt prisam.shcema

---

src/middleware/thread.DTO/thread.DTO.ts
src/thread/thread.Controller.ts
src/thread/thread.Model.ts
src/thread/thread.Service.ts

예시:
- 관련 이슈: #45
#147 
---
---
예시:
게시글 이미지 업로드 로직을 변경했습니다. 이제 이미지를 먼저 업로드하고 url을 반환한뒤 게시글에 url을 저장하는 방식입니다.
---
예시:
---

[refactor] 게시글 이미지 업로드 플로우 수정

---

src/config/fcm.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: FireBase setting

---

.github/workflows/backup.yml
.github/workflows/deploy.yml

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: firebase  problem

---

src/config/fcm.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix firebase

---

.github/workflows/backup.yml
.github/workflows/deploy.yml
src/config/fcm.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

\n problem in Firebase

---

.github/workflows/backup.yml
.github/workflows/deploy.yml

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix firebase \n problem

---

.github/workflows/backup.yml
.github/workflows/deploy.yml

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: fcm.ts to  and \n

---

.github/workflows/deploy.yml

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: deploy command

---

.github/workflows/deploy.yml
src/config/fcm.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: deploy

---

.github/workflows/backup.yml
.github/workflows/deploy.yml

- 관련 이슈: #178 
---
---
예시:
---
예시:
---

fix: mongodb deploy yml

---

src/config/fcm.ts

- 관련 이슈: #184 
---
---
* FCM에서 환경 변수로 받아야하는 값이 총 3가지가 존재
1. FIREBASE_PROJECT_ID
2. FIREBASE_CLIENT_EMAIL
3. FIREBASE_PRIVATE_KEY
중 1번 누락으로 생긴 현상.
---
예시:
---

[fix] projectId value

---

src/config/fcm.ts

예시:
- 관련 이슈: #186 
---
---
FCM 환경변수 에러 코드 세분화
---
예시:
---

[fix] error Detection coded added

---

.github/workflows/deploy.yml

…nged
- 관련 이슈: #187 
---
---
Prisma Client 생성 (SQL + mongoDB 추가)
npm run dev -> npm run start  수정
---
예시:
---

[fix] CICD Deploy code 

---

.github/workflows/deploy.yml

예시:
- 관련 이슈: #189 
---
---
* 에러 로그 명시화
* nohub 파일 확인
* nohup이 존재하지 않다면 설치 요구
---
예시:
---

[fix] deploy yml file

---

.github/workflows/deploy.yml

- 관련 이슈: #190 
---
---
* npm run start to dev
---
예시:
---

[fix] application start to dev

---

src/chat/chat.Controller.ts
src/chat/chat.Model.ts
src/chat/chat.Service.ts
src/socket/socket.message.ts

예시:
- 관련 이슈: #193 
---
---
* Chat room에서 사진 업로드
---
예시:
---

[feat] photo upload in chat room

---

src/alert/alert.Controller.ts
src/config/fcm.ts
src/socket/socket.model.ts
src/socket/socket.service.ts

예시:
- 관련 이슈: #45
---
---
* 추가적인 주석 처리
---
* FCM 주석 처리 정보 상세화
---

[fix] FCM 주석 처리

---

src/middleware/univ.DTO/univ.DTO.ts
src/thread/thread.Controller.ts
src/thread/thread.Service.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix:lookup typo fix

---

src/alert/alert.Controller.ts
src/alert/alert.Service.ts
src/coffeeChat/coffeeChat.Service.ts
src/config/fcm.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: FCM Error fix

---

src/thread/thread.Controller.ts

예시:
- 관련 이슈: #45
---
---
예시:
이미지가 없을 때 게시글 업로드가 될 수 있도록 수정
---
예시:
---

[fix] 이미지 없이 게시글 업로드

---

src/config/fcm.ts

- 관련 이슈: #227 
---
---
예시:
---
예시:
---

[fix] device changed

---

src/coffeeChat/coffeeChat.Controller.ts
src/coffeeChat/coffeeChat.Model.ts
src/coffeeChat/coffeeChat.Service.ts
src/config/fcm.ts
src/middleware/coffectChat.DTO/coffectChat.DTO.ts
src/user/user.Model.ts
src/user/user.Service.ts

- 관련 이슈: #230 
---
---
* CoffeeChat 메세지 보기 API 만듬.
* Logout 시 FCM Token 삭제 기능 추가
---
예시:
---

[feat] coffeechat 보여주기

---

src/user/user.Controller.ts
src/user/user.Model.ts
src/user/user.Service.ts

- 관련 이슈: #233 
---
---
* 회원 탈퇴 구현 완료
---
예시:
---

[feat] 회원 탈퇴 구현 완료

---

src/chat/chat.Controller.ts
src/chat/chat.Model.ts
src/chat/chat.Service.ts

- 관련 이슈: #235 
---
---
Front에서 500에러로 인한 try catch 보완 밑 에러 상세화
---
예시:
---

[fix] Chat 관련 Try catch로 감쌈

---

prisma/mysql/schema.prisma
src/config/fcm.ts

- 관련 이슈: #237 
---
---
* FCM 포맷 변경
---
예시:
---

[refac] FCM 포맷 변경

---

prisma/mysql/schema.prisma
src/config/fcm.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

[fix] prisma db

---

src/config/fcm.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

Refac/jun fcm 알림 전송 포맷 변경

---

src/socket/socket.message.ts
src/socket/socket.model.ts
src/socket/socket.service.ts
src/socket/socket.ts

- 관련 이슈: #241 
---
---
* MongoDb Transection 제거
* MongoDB 접속 에러 세분화
* Socket 접속 에러 세분화
---
예시:
---

[fix] add socket error specify

---

src/middleware/socket.DTO/socket.DTO.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: type error

---

src/middleware/thread.DTO/thread.DTO.ts
src/thread/thread.Controller.ts
src/thread/thread.Model.ts
src/thread/thread.Service.ts

예시:
- 관련 이슈: #45
#217 
---
---
예시:
게시글에 좋아요 유무, 스크랩 유무, 팔로우 유무가 표시되도록 했습니다.
---
예시:
---

refactor: contain additional info

---

src/middleware/thread.DTO/thread.DTO.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

refac: add id in thread/main

---

src/middleware/thread.DTO/thread.DTO.ts
src/thread/thread.Model.ts

예시:
- 관련 이슈: #45
#218 
---
---
예시:
댓글 응답에 유저 아이디와 학과 정보 추가
---
예시:
---

refactor: 댓글에 학과 추가

---

src/profile/profile.Service.ts
src/user/user.Model.ts
src/user/user.Service.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix : FCM 허용 안해도 로그아웃되도록 구현

---

src/profile/profile.Model.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

refacor : 쓰레드 조회 추가

---

src/profile/profile.Controller.ts
src/profile/profile.Model.ts
src/profile/profile.Service.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

refactor : 진짜 고침

---

src/coffeeChat/coffeeChat.Model.ts
src/config/fcm.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix userId changed

---

src/index.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

feat : websocket 변경

---

src/config/fcm.ts
src/profile/profile.Model.ts
src/user/user.Model.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

refactor : 회원가입시 기본 질문리스트 추가

---

src/follow/follow.Controller.ts
src/follow/follow.Model.ts
src/follow/follow.Service.ts
src/middleware/follow.DTO/follow.DTO.ts

- 관련 이슈: #274 
---
---
* follower following 목록 조회 api 만듬
---
예시:
---

[feat] follower following add

---

src/coffeeChat/coffeeChat.Model.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix schedule

---

src/socket/socket.ts

예시:
- 관련 이슈: #45
---
---
예시:
---
예시:
---

fix: tostring 수정

---

src/chat/chat.Model.ts

예시:
- 관련 이슈: #45
---
---
* Socket 채팅 시 정상적으로 KST 시간으로 표기됨
* API Call 시 UTF 시간으로 다시 변경되는 문제 해결
-> DB에서 Z인자가 붙어 UTF 시간으로 변환이됨.
---
예시:
---

[fix] Chat Api UTF time
